"""
CSV 导出引擎单元测试（query-result-export-plan）。

覆盖：
  - 字段转义（逗号/引号/换行）
  - 表头含水印与敏感标注
  - 分批流式输出 + 行数上限截断标注
  - 空结果集仍产出表头
  - 流中途异常 → 输出错误标注行（不抛 500）
"""

from __future__ import annotations

import pytest

from app.engine.csv_exporter import (
    build_export_header,
    escape_csv_field,
    iter_csv_rows,
    with_first_batch_timeout,
)


class TestEscapeCsvField:
    def test_plain_value(self) -> None:
        assert escape_csv_field("abc") == "abc"

    def test_comma_quoted(self) -> None:
        assert escape_csv_field("a,b") == '"a,b"'

    def test_quote_doubled(self) -> None:
        assert escape_csv_field('say "hi"') == '"say ""hi"""'

    def test_newline_quoted(self) -> None:
        assert escape_csv_field("line1\nline2") == '"line1\nline2"'

    def test_none_becomes_empty(self) -> None:
        assert escape_csv_field(None) == ""


class TestBuildExportHeader:
    def test_watermark_and_columns(self) -> None:
        lines = build_export_header(["id", "name"], [False, False])
        assert lines[0].startswith("﻿# Generated by DB-Pilot")
        assert lines[1] == "id,name"
        assert "# [包含敏感字段]" not in lines

    def test_sensitive_marker(self) -> None:
        lines = build_export_header(["phone"], [True])
        assert "# [包含敏感字段]" in lines
        assert "phone 🔒" in lines


class TestIterCsvRows:
    async def _fake_stream(self, data):
        yield ["id", "name"], data[0]
        yield ["id", "name"], data[1]

    @pytest.mark.asyncio
    async def test_streams_all_rows(self) -> None:
        async def _stream():
            yield ["id", "name"], [[1, "alice"], [2, "bob"]]

        lines = []
        async for line in iter_csv_rows(_stream(), max_rows=10):
            lines.append(line)

        body = "".join(lines)
        assert "1,alice" in body
        assert "2,bob" in body
        assert "结果已截断" not in body

    @pytest.mark.asyncio
    async def test_truncates_at_max_rows(self) -> None:
        async def _stream():
            yield ["id", "name"], [[1, "a"], [2, "b"], [3, "c"]]

        lines = []
        async for line in iter_csv_rows(_stream(), max_rows=2):
            lines.append(line)

        body = "".join(lines)
        assert "3,c" not in body
        assert "结果已截断至 2 行（导出上限）" in body

    @pytest.mark.asyncio
    async def test_masks_sensitive_values(self) -> None:
        async def _stream():
            yield ["id", "password"], [[1, "secret"]]

        lines = []
        async for line in iter_csv_rows(_stream(), max_rows=10):
            lines.append(line)

        body = "".join(lines)
        assert "1,***" in body
        assert "secret" not in body

    @pytest.mark.asyncio
    async def test_empty_result_still_writes_header(self) -> None:
        async def _stream():
            yield ["id", "name"], []

        lines = []
        async for line in iter_csv_rows(_stream(), max_rows=10):
            lines.append(line)

        assert any("id,name" in line for line in lines)

    @pytest.mark.asyncio
    async def test_midstream_error_yields_error_line(self) -> None:
        async def _stream():
            yield ["id"], [[1]]
            raise RuntimeError("断流")

        lines = []
        async for line in iter_csv_rows(_stream(), max_rows=10):
            lines.append(line)

        assert any(line.startswith("# 导出失败") for line in lines)


class TestWithFirstBatchTimeout:
    @pytest.mark.asyncio
    async def test_passes_through_batches(self) -> None:
        async def _stream():
            yield ["id"], [[1]]
            yield ["id"], [[2]]

        got = []
        async for item in with_first_batch_timeout(_stream(), timeout_sec=5):
            got.append(item)
        assert len(got) == 2

    @pytest.mark.asyncio
    async def test_times_out_on_first_batch(self) -> None:
        import asyncio

        async def _slow_stream():
            await asyncio.sleep(0.2)
            yield ["id"], [[1]]

        with pytest.raises(TimeoutError):
            async for _ in with_first_batch_timeout(_slow_stream(), timeout_sec=0.01):
                pass
