/**
 * 结果导出 composable
 *
 * 支持 CSV（前端纯 Blob）和 Excel（xlsx 库）两种格式，
 * 含敏感列默认排除 + 导出水印。
 *
 * 依据 frontend AGENTS.md §2 复制与导出限制
 *     api-contract T-4（列名正则 + is_sensitive 双重判定）
 */
import { ref, reactive, computed } from 'vue'
import { isColumnSensitive } from './useSensitiveData'
import type { QueryColumn } from '@/types/chat'

// ─── xlsx 动态导入 ───

let _XLSX: typeof import('xlsx') | null = null

async function getXLSX(): Promise<typeof import('xlsx')> {
  if (!_XLSX) {
    _XLSX = await import('xlsx')
  }
  return _XLSX
}

// ─── 水印 ───

const WATERMARK_TEXT = `Generated by DB-Pilot | ${new Date().toISOString()} UTC`

/** 文件名前缀（安全转义） */
function safeFileName(prefix: string = 'export'): string {
  const timestamp = Date.now()
  return `${prefix}_${timestamp}`
}

// ─── Export 状态 ───

export interface ExportOptions {
  /** 列定义 */
  columns: QueryColumn[]
  /** 行数据（字符串二维数组） */
  rows: string[][]
  /** 文件名前缀 */
  fileName?: string
}

export function useExport() {
  // ─── 对话框状态 ───

  const showDialog = ref(false)
  const exportFormat = ref<'csv' | 'excel'>('csv')
  const exporting = ref(false)

  // ─── 列选择 ───

  const columns = ref<QueryColumn[]>([])
  const rows = ref<string[][]>([])
  const fileName = ref('export')

  /** 各列是否敏感 */
  const sensitiveFlags = ref<boolean[]>([])

  /** 选中的列索引 */
  const selectedColumns = reactive<Set<number>>(new Set())

  /** 选中列包含敏感列吗？ */
  const hasSensitiveSelected = computed(() => {
    return Array.from(selectedColumns).some((idx) => sensitiveFlags.value[idx])
  })

  // ─── 打开导出对话框 ───

  function openExport(format: 'csv' | 'excel', opts: ExportOptions): void {
    exportFormat.value = format
    columns.value = opts.columns
    rows.value = opts.rows
    fileName.value = opts.fileName ?? 'export'

    // 计算敏感标志
    sensitiveFlags.value = opts.columns.map((col) =>
      isColumnSensitive(col.name, col.is_sensitive)
    )

    // 默认：非敏感列全选，敏感列不选
    selectedColumns.clear()
    opts.columns.forEach((_, idx) => {
      if (!sensitiveFlags.value[idx]) {
        selectedColumns.add(idx)
      }
    })

    showDialog.value = true
  }

  // ─── 切换列选择 ───

  function toggleColumn(idx: number): void {
    if (selectedColumns.has(idx)) {
      // 敏感列可以手动取消
      selectedColumns.delete(idx)
    } else {
      // 任何列都可以被选中
      selectedColumns.add(idx)
    }
    // 强制响应式通知
  }

  // ─── 关闭对话框 ───

  function cancelExport(): void {
    showDialog.value = false
  }

  // ─── 执行导出 ───

  async function confirmExport(): Promise<void> {
    if (selectedColumns.size === 0) return

    exporting.value = true

    try {
      // 构建选中的列名和行数据
      const selectedIndices = Array.from(selectedColumns).sort((a, b) => a - b)
      const colNames = selectedIndices.map((idx) => columns.value[idx].name)
      const colSensitive = selectedIndices.map((idx) => sensitiveFlags.value[idx])
      const dataRows = rows.value.map((row) =>
        selectedIndices.map((idx) => row[idx] ?? '')
      )

      if (exportFormat.value === 'csv') {
        downloadCSV(colNames, colSensitive, dataRows)
      } else {
        await downloadExcel(colNames, colSensitive, dataRows)
      }

      showDialog.value = false
    } catch (err) {
      console.error('[Export] 导出失败:', err)
    } finally {
      exporting.value = false
    }
  }

  // ─── CSV 导出 ───

  function downloadCSV(
    colNames: string[],
    colSensitive: boolean[],
    dataRows: string[][]
  ): void {
    const lines: string[] = []

    // 水印注释
    lines.push(`# ${WATERMARK_TEXT}`)

    // 敏感字段标记
    const hasSensitive = colSensitive.some((s) => s)
    if (hasSensitive) {
      lines.push(`# [包含敏感字段]`)
    }

    // CSV 转义
    function escapeCSV(val: string): string {
      if (val.includes(',') || val.includes('"') || val.includes('\n')) {
        return `"${val.replace(/"/g, '""')}"`
      }
      return val
    }

    // 列头
    const headerRow = colNames.map((name, i) => {
      const marker = hasSensitive && colSensitive[i] ? ' 🔒' : ''
      return escapeCSV(`${name}${marker}`)
    })
    lines.push(headerRow.join(','))

    // 数据行
    for (const row of dataRows) {
      lines.push(row.map((cell) => escapeCSV(cell)).join(','))
    }

    // 页脚水印
    lines.push(`# ${WATERMARK_TEXT}`)

    const bom = '﻿'
    const blob = new Blob([bom + lines.join('\n')], {
      type: 'text/csv;charset=utf-8',
    })
    triggerDownload(blob, `${safeFileName(fileName.value)}.csv`)
  }

  // ─── Excel 导出 ───

  async function downloadExcel(
    colNames: string[],
    colSensitive: boolean[],
    dataRows: string[][]
  ): Promise<void> {
    const XLSX = await getXLSX()

    // 构建数据数组
    const wsData: unknown[][] = []

    // 水印行
    wsData.push([WATERMARK_TEXT])
    wsData.push([]) // 空行

    // 敏感字段标记行
    const hasSensitive = colSensitive.some((s) => s)
    if (hasSensitive) {
      wsData.push([`[包含敏感字段] ${colNames.filter((_, i) => colSensitive[i]).join(', ')}`])
    }

    // 列头
    const headerRow = colNames.map((name, i) => {
      const marker = hasSensitive && colSensitive[i] ? '🔒' : ''
      return `${marker}${name}`
    })
    wsData.push(headerRow)

    // 数据行
    for (const row of dataRows) {
      wsData.push(row)
    }

    // 空行 + 页脚水印
    wsData.push([])
    wsData.push([WATERMARK_TEXT])

    const wb = XLSX.utils.book_new()
    const ws = XLSX.utils.aoa_to_sheet(wsData)

    // 设置列宽
    ws['!cols'] = colNames.map(() => ({ wch: 20 }))

    XLSX.utils.book_append_sheet(wb, ws, 'QueryResult')

    const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
    const blob = new Blob([wbout], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    })
    triggerDownload(blob, `${safeFileName(fileName.value)}.xlsx`)
  }

  // ─── Blob 下载 ───

  function triggerDownload(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return {
    // 状态
    showDialog,
    exportFormat,
    exporting,
    columns,
    sensitiveFlags,
    selectedColumns,
    hasSensitiveSelected,

    // 动作
    openExport,
    toggleColumn,
    cancelExport,
    confirmExport,
  }
}
