"""
CSV 导出引擎（query-result-export-plan）。

将 (columns, rows_batch) 流转换为带安全标注的 CSV 文本行流：
  - UTF-8 BOM（Excel 打开中文不乱码）
  - 水印 + 敏感字段标注
  - 逐批掩码 + CSV 转义，内存有界
  - 行数硬上限截断标注
  - 首批拉取超时控制（查询执行超时）

供导出端点 POST /api/connections/{id}/export 使用。
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator
from typing import Any

from app.engine.data_masking import mask_query_result

# 水印前缀（与前端 useExport.ts 的 WATERMARK_TEXT 同源）
_WATERMARK = "Generated by DB-Pilot | {ts} UTC"


def _utc_now_str() -> str:
    """UTC 当前时间字符串（%Y-%m-%d %H:%M:%S）。"""
    import datetime

    return datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")


def escape_csv_field(value: Any) -> str:
    """转义单个 CSV 字段（含逗号/引号/换行时用引号包裹，双写内部引号）。"""
    s = "" if value is None else str(value)
    if "," in s or '"' in s or "\n" in s or "\r" in s:
        return '"' + s.replace('"', '""') + '"'
    return s


def build_export_header(columns: list[str], sensitive_flags: list[bool]) -> list[str]:
    """构造 CSV 头部文本行（BOM + 水印 + 敏感标注 + 列头）。

    Args:
        columns: 列名列表。
        sensitive_flags: 各列是否敏感（与 columns 等长）。

    Returns:
        不含换行的文本行列表。
    """
    lines = [f"﻿# {_WATERMARK.format(ts=_utc_now_str())}"]
    has_sensitive = any(sensitive_flags)
    if has_sensitive:
        lines.append("# [包含敏感字段]")
    header = [
        f"{escape_csv_field(c)} 🔒" if has_sensitive and f else escape_csv_field(c)
        for c, f in zip(columns, sensitive_flags, strict=True)
    ]
    lines.append(",".join(header))
    return lines


def build_truncation_note(max_rows: int) -> str:
    """构造截断标注文本行。"""
    return f"# 结果已截断至 {max_rows} 行（导出上限）"


async def with_first_batch_timeout(
    rows_iterator: AsyncIterator[tuple[list[str], list[list[Any]]]],
    timeout_sec: float,
) -> AsyncIterator[tuple[list[str], list[list[Any]]]]:
    """对首批拉取施加超时（查询执行阶段），后续批次由行数上限兜底。"""
    it = rows_iterator.__aiter__()
    try:
        first = await asyncio.wait_for(it.__anext__(), timeout=timeout_sec)
    except StopAsyncIteration:
        return
    yield first
    async for item in it:
        yield item


async def iter_csv_rows(
    rows_iterator: AsyncIterator[tuple[list[str], list[list[Any]]]],
    max_rows: int,
) -> AsyncIterator[str]:
    """将 (columns, rows_batch) 流转换为 CSV 文本行流。

    Args:
        rows_iterator: 产出 (columns, rows_batch) 的异步迭代器。
        max_rows: 单次导出行数硬上限，超出截断并追加标注。

    Yields:
        CSV 文本行（含换行）。流中途异常时产出错误标注行后终止。
    """
    first = True
    count = 0
    truncated = False
    try:
        async for columns, batch in rows_iterator:
            if first:
                flags, _ = mask_query_result(columns, None)
                for line in build_export_header(columns, flags):
                    yield line + "\n"
                first = False
            _, masked = mask_query_result(columns, batch)
            for row in masked:
                if count >= max_rows:
                    truncated = True
                    break
                yield ",".join(escape_csv_field(v) for v in row) + "\n"
                count += 1
            if truncated:
                break
    except Exception as exc:
        yield f"# 导出失败: {str(exc)[:200]}\n"
        return
    if truncated:
        yield build_truncation_note(max_rows) + "\n"
